### ISSUE TITLE
Add energy and health bars that deplete and replenish

### ISSUE THREAD

**Issue by kanerogers** [kanerogers/clipper#29]
This'll be fun

## TODO
- [x] Get some sort of rectangle going
- [x] Make the rectangle move as a progress bar
- [x] Align it properly
