### ISSUE TITLE
Add in-game clock with cycles (work / rest)

### ISSUE THREAD

**Issue by kanerogers** [kanerogers/clipper#38]
# TODO
- [x] Add a `Clock` struct
- [x] Advance by `dt` each frame
- [x] Specify some conversion between wall clock and in-game clock (ie. 1 wall second is 1 in-game minute)
- [x] Show clock in bottom right corner
