### ISSUE TITLE
Add resting, eating, etc.

### ISSUE THREAD

**Issue by kanerogers** [kanerogers/clipper#39]
## TODO
- [x] Get farm model
- [x] Add `Resource::Food`
- [x] Add `PlaceOfWork::Farm` that produces `Resource::Food`
- [x] Get house model
- [x] Add `struct House { occupants: Vec<Entity>, capacity: usize }`
- [x] Add `HumanNeeds { sleep: usize, food: usize }` component
- [x] Switch to `viking_behaviour` system and check if `is_work_time()`
- [x] Add `rest_behaviour` function. First eat, then sleep.

**Comment by kanerogers** [comment]
Closed by #63
